audit_header: false
title: OsteoStrong – The Ultimate Biohack | Osteogenic Loading
description: OsteoStrong is a unique system focused on developing your skeletal strength and improving your bone health. It is the ultimate biohack.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Free Session
    url: https://www.osteostrong.me/free-session/

client:
  name: Tiffany Canady
  title:
  license_number:
  about_markdown: |
    My goal is to educate, support and empower everyone I work with! I am driven to provide the community with an alternative solution to heal themselves without depending on pain medications and injections. I am committed to helping people realize their own potential and achieve vibrant health!

    Our team takes an integrative approach to wellness, with natural ways to relieve stress, build bone, improve strength, balance, posture,and pure power as well as relieve back and joint pain. Our system promotes skeletal strength and conditioning and has shown to reverse Osteoporosis and prevent Low Bone Density. We customize programs to the individual to support optimal health and well-being.
  brand: OsteoStrong
  brokerage:
  market:
  address: 5992 Stetson Hills Blvd.<br>Colorado Springs, CO 80923
  phone: 877-893-0008
  phone_type:
  phone2:
  phone2_type:
  email: Canady@OsteoStrong.me
  url: http://osteostrongcoloradosprings.com

# CTAs:t
#   first_CTA_text: Home Valuation
#   first_CTA_URL: /homevalue/
#   second_CTA_text: Home Search
#   second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "NO PAIN | ALL GAIN"
    CTA_text: "60 Seconds to Pure Power. The Ultimate Biohack"
    CTA_link_text: "Get a Free Session"
    CTA_url: https://www.osteostrong.me/free-session/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/osteostrong
  linkedin_url:
  youtube_url: https://www.youtube.com/user/osteostrong
  twitter_url: https://twitter.com/OsteoStrong
  instagram_url: https://www.instagram.com/osteostrong.me
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'OsteoStrong'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'The Ultimate Biohack | Osteogenic Loading'
  description: 'OsteoStrong is a unique system focused on developing your skeletal strength and improving your bone health. It is the ultimate biohack.'
  keywords: 'Osteo, Osteostrong, Bone strength, Bone density, Bone, Biodensity, Skeletal development, Osteoporosis, Biohack, Osteogenic Loading'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: OsteoStrong | The Ultimate Biohack
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#555555'
  accent_color: '#fec749'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
